/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const LongBuilding = forwardRef(function LongBuilding({level, ...props},ref) {
  const { nodes, materials } = useGLTF('/building3x1.glb')
  return (
    <group name="objectGroup" ref={ref} {...props} scale={[props.scale, props.scale * (level*2+1), props.scale]}dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Concrete}
        position={[7.2, 0, -0.89]}
        scale={[19.02, 0.85, 63.78]}
      />
      <group position={[3.5, 0, 0]} scale={[15, 1, 40]}>
        <mesh receiveShadow geometry={nodes.Plane005_1.geometry} material={materials["grass.004"]} />
        <mesh receiveShadow geometry={nodes.Plane005_2.geometry} material={materials["grass.001"]} />
        <mesh receiveShadow geometry={nodes.Plane005_3.geometry} material={materials["grass.002"]} />
        <mesh receiveShadow geometry={nodes.Plane005_4.geometry} material={materials["grass.003"]} />
      </group>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.GaragesDouble.geometry}
        material={materials["Material.004"]}
        position={[20.57, 0.58, -37.78]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[5.67, 0.75, 7.23]}
      />
      <group position={[13.26, 0.65, -37.78]} rotation={[0, Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube008.geometry} material={materials["Material.002"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube008_1.geometry} material={materials["Material.003"]} />
      </group>
      <group position={[13.26, 0.65, -26.45]} rotation={[0, Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube009.geometry} material={materials["Material.002"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube009_1.geometry} material={materials["Material.003"]} />
      </group>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.GaragesDouble001.geometry}
        material={materials["Material.004"]}
        position={[-20.18, 0.58, -26.23]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[5.67, 0.75, 7.23]}
      />
      <group position={[-12.87, 0.65, -26.23]} rotation={[0, -Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube012.geometry} material={materials["Material.002"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube012_1.geometry} material={materials["Material.003"]} />
      </group>
      <group position={[-12.87, 0.65, -37.56]} rotation={[0, -Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials["Material.002"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials["Material.003"]} />
      </group>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.GaragesDouble002.geometry}
        material={materials["Material.004"]}
        position={[-5.08, 0.58, -55.88]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[5.67, 0.75, 7.23]}
      />
      <group position={[-5.08, 0.65, -48.57]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube018.geometry} material={materials["Material.002"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube018_1.geometry} material={materials["Material.003"]} />
      </group>
      <group position={[6.25, 0.65, -48.57]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube019.geometry} material={materials["Material.002"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube019_1.geometry} material={materials["Material.003"]} />
      </group>
      <group position={[-0.49, -0.1, 25.17]} rotation={[0, Math.PI / 2, 0]} scale={[3.73, 0.07, 3.28]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube.geometry} material={materials.darker_snow} />
        <mesh receiveShadow castShadow geometry={nodes.Cube_1.geometry} material={materials.brown} />
      </group>
      <group position={[-0.49, 0.05, 42.1]} rotation={[0, Math.PI / 2, 0]} scale={[10.55, -0.22, 19.21]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube001.geometry} material={materials.floortile} />
        <mesh receiveShadow castShadow geometry={nodes.Cube001_1.geometry} material={materials["Material.001"]} />
      </group>
      <group position={[-0.51, 2.66, 28.82]} rotation={[0, Math.PI / 2, 0]} scale={[0.14, 0.86, 0.75]}>
        <mesh receiveShadow castShadow geometry={nodes.knob.geometry} material={materials.brown} />
        <mesh receiveShadow castShadow geometry={nodes.knob_1.geometry} material={materials.shiny} />
        <mesh receiveShadow castShadow geometry={nodes.knob_2.geometry} material={materials.snow} />
        <mesh receiveShadow castShadow geometry={nodes.knob_3.geometry} material={materials.floortile} />
      </group>
      <group position={[6.79, 23.42, 28.93]} rotation={[0, -Math.PI / 2, 0]} scale={[0.15, 2.12, 2.39]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube013.geometry} material={materials["brown.005"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube013_1.geometry} material={materials["shiny.005"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube013_2.geometry} material={materials["snow.005"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube013_3.geometry} material={materials["brown.006"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube013_4.geometry} material={materials["shiny.006"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube013_5.geometry} material={materials["snow.006"]} />
      </group>
      <group position={[6.79, 38.33, 28.93]} rotation={[0, -Math.PI / 2, 0]} scale={[0.15, 2.12, 2.39]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube015.geometry} material={materials["brown.009"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube015_1.geometry} material={materials["shiny.009"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube015_2.geometry} material={materials["snow.009"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube015_3.geometry} material={materials["brown.010"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube015_4.geometry} material={materials["shiny.010"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube015_5.geometry} material={materials["snow.010"]} />
      </group>
      <group position={[6.79, 7.75, 28.93]} rotation={[0, -Math.PI / 2, 0]} scale={[0.15, 2.12, 2.39]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube011.geometry} material={materials["brown.004"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube011_1.geometry} material={materials["shiny.004"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube011_2.geometry} material={materials["snow.004"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube011_3.geometry} material={materials["brown.003"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube011_4.geometry} material={materials["shiny.003"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube011_5.geometry} material={materials["snow.003"]} />
      </group>
      <group position={[6.79, 53.99, 28.93]} rotation={[0, -Math.PI / 2, 0]} scale={[0.15, 2.12, 2.39]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube014.geometry} material={materials["brown.008"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube014_1.geometry} material={materials["shiny.008"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube014_2.geometry} material={materials["snow.008"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube014_3.geometry} material={materials["brown.007"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube014_4.geometry} material={materials["shiny.007"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube014_5.geometry} material={materials["snow.007"]} />
      </group>
      <group position={[-13.73, 0.34, 70.73]} rotation={[2.05, -1.42, 2.06]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder_1.geometry} material={materials["brown.011"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder_2.geometry} material={materials.green2} />
      </group>
      <group position={[20.31, 0.34, 70.43]} rotation={[0.2, -0.85, 0.16]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder002_1.geometry} material={materials["brown.012"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder002_2.geometry} material={materials["green2.001"]} />
      </group>
      <group position={[-27.71, 0.34, 41.03]} rotation={[0.14, -0.16, 0.03]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder010.geometry} material={materials["brown.016"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder010_1.geometry} material={materials["green2.005"]} />
      </group>
      <group position={[-26.41, 0.34, 31.42]} rotation={[0.14, -0.33, 0.05]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder013.geometry} material={materials["brown.019"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder013_1.geometry} material={materials["green2.008"]} />
      </group>
      <group position={[-26.26, 0.34, 63.95]} rotation={[-0.14, -1.13, -0.16]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder006.geometry} material={materials["brown.011"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder006_1.geometry} material={materials.green2} />
      </group>
      <group position={[-21.89, 0.34, 72.92]} rotation={[-0.01, 0.01, -0.13]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder007.geometry} material={materials["brown.011"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder007_1.geometry} material={materials.green2} />
      </group>
      <group position={[5.26, 0.34, -69.59]} rotation={[-0.01, -0.17, -0.13]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder004.geometry} material={materials["brown.014"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder004_1.geometry} material={materials["green2.003"]} />
      </group>
      <group position={[-1.85, 0.34, 67.95]} rotation={[-0.13, 1.49, 0]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder009.geometry} material={materials["brown.015"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder009_1.geometry} material={materials["green2.004"]} />
      </group>
      <group position={[27.86, 0.34, 55.15]} rotation={[-0.14, -1.13, -0.16]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder008.geometry} material={materials["brown.011"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder008_1.geometry} material={materials.green2} />
      </group>
      <group position={[10.2, 0.34, 65.44]} rotation={[-0.06, -0.35, -0.06]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder001_1.geometry} material={materials["brown.012"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder001_2.geometry} material={materials["green2.001"]} />
      </group>
      <group position={[-5.27, 0.34, 73.27]} rotation={[-3, -1.13, -3.06]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder005.geometry} material={materials["brown.013"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder005_1.geometry} material={materials["green2.002"]} />
      </group>
      <group position={[20.32, 0.34, -73.15]} rotation={[-0.22, -1.3, -0.25]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder003.geometry} material={materials["brown.014"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder003_1.geometry} material={materials["green2.003"]} />
      </group>
      <group position={[-24.04, 0.34, -75.05]} rotation={[-0.22, -1.3, -0.25]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder011.geometry} material={materials["brown.017"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder011_1.geometry} material={materials["green2.006"]} />
      </group>
      <group position={[-27.75, 0.34, -61.29]} rotation={[-0.1, 0.96, 0.04]} scale={0.75}>
        <mesh receiveShadow castShadow geometry={nodes.Cylinder012.geometry} material={materials["brown.018"]} />
        <mesh receiveShadow castShadow geometry={nodes.Cylinder012_1.geometry} material={materials["green2.007"]} />
      </group>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cone.geometry}
        material={materials["rock.002"]}
        position={[-25.22, -0.1, 67.1]}
        rotation={[Math.PI, -1.28, Math.PI]}
        scale={0.75}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cone001.geometry}
        material={materials["rock.002"]}
        position={[5, -0.1, 72.33]}
        rotation={[Math.PI, -0.08, Math.PI]}
        scale={1.26}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["rock.001"]}
        position={[25.23, -0.16, 66.34]}
        rotation={[Math.PI, -1.14, Math.PI]}
        scale={1.33}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["rock.001"]}
        position={[-15.84, -0.9, -72.43]}
        rotation={[0.36, 0.23, 0]}
        scale={1.33}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["rock.003"]}
        position={[-28.51, -0.9, 52.77]}
        rotation={[0.35, -0.09, 0.12]}
        scale={1.33}
      />
    </group>
  );
})

useGLTF.preload('/building3x1.glb')
export default LongBuilding