/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Factory({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Factory.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.Plane001.geometry} material={materials['grass.002']} scale={[30, 1, 30]} />
      <group position={[-20, 1, 0]} scale={[29.4, 1, -66.88]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={materials.floortile} />
        <mesh castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={materials.snow} />
      </group>
      <group position={[-6.3, 25.6, -40]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-10.3, 25.6, -40]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-14.3, 25.6, -40]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-18.3, 25.6, -40]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-22.3, 25.6, -40]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -7]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -11]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -19]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -15]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -23]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -27]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -35]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -31]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 1]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -3]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 5]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 9]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 17]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 13]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 57]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 53]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 45]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 49]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 41]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 37]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 33]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 61]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -48]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -44]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -52]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -56]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -64]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -60]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -60]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -64]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -56]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -52]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -44]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -48]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -60]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -64]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -56]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -52]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -44]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -48]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -24]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -20]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -28]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -32]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -40]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -36]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -16]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[3, 13.4, -66.8]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-4, 13.4, -66.8]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-11, 13.4, -66.8]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-18, 13.4, -66.8]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-25, 13.4, -66.8]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-32, 13.4, -66.8]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -38.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -31.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -45.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -24.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -59.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -52.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -10.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -17.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 17.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -3.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 10.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 3.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 45.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 52.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 38.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 59.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 24.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 31.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 62.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 56.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 50.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 44.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 38.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 32.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 20.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 26.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 8.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 14.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, -9.4]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, -3.4]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 2.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <mesh receiveShadow geometry={nodes.Plane002.geometry} material={materials.Concrete} scale={[48.5, 1, 66.6]} />
    </group>
  )
}

useGLTF.preload('/Factory.glb')
