/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Factory = forwardRef(function Factory(props,ref) {
  const { nodes, materials } = useGLTF('/Factory.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.Plane001.geometry} material={materials['grass.002']} scale={[30, 1, 40]} />
      <group position={[-20, 1, 27]} scale={[29.4, 1, -66.88]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube007.geometry} material={materials.floortile} />
        <mesh receiveShadow castShadow geometry={nodes.Cube007_1.geometry} material={materials.snow} />
      </group>
      <group position={[-6.3, 25.6, -13]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-10.3, 25.6, -13]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-14.3, 25.6, -13]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-18.3, 25.6, -13]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-22.3, 25.6, -13]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 20]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 16]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 8]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 12]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 4]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -8]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, -4]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 28]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 24]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 32]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 36]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 44]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 40]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 48]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 52]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 84]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 80]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 72]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 76]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 68]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 64]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 56]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 60]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-2.3, 25.6, 88]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -17]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -37]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -33]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -33]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -37]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -17]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 25.6, -21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -33]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -37]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -25]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -17]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -21]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, 3]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, 7]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -1]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -5]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -13]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, -9]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-37.7, 34.6, 11]} rotation={[0, -Math.PI / 2, 0]} scale={[0.8, 3.4, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube016.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube016_1.geometry} material={materials.shiny} />
      </group>
      <group position={[3, 13.4, -39.8]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-4, 13.4, -39.8]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-11, 13.4, -39.8]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-18, 13.4, -39.8]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-25, 13.4, -39.8]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-32, 13.4, -39.8]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -11.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -4.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -18.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 2.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -32.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, -25.3]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 16.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 9.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 44.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 23.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 37.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 30.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 72.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 79.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 65.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 86.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 51.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[9.3, 13.4, 58.7]} rotation={[0, -Math.PI / 2, 0]} scale={[2, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube053.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube053_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 89.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 83.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 77.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 71.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 65.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 59.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 47.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 53.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 35.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 41.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 17.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 23.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <group position={[-26, 34.1, 29.6]} rotation={[0, -Math.PI / 2, 0]} scale={[1.6, 1, 1]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube085.geometry} material={materials.Metal} />
        <mesh receiveShadow castShadow geometry={nodes.Cube085_1.geometry} material={materials.shiny} />
      </group>
      <mesh receiveShadow geometry={nodes.Plane002.geometry} material={materials.Concrete} position={[0, 0, 27]} scale={[48.5, 1, 66.6]} />
      <group position={[-37.04, 0.65, -87.95]} rotation={[0, -Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube001.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-37.04, 0.65, -76.62]} rotation={[0, -Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube006.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube006_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-37.04, 0.65, -65.28]} rotation={[0, -Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube005.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube005_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-37.04, 0.65, -53.94]} rotation={[0, -Math.PI / 2, 0]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube004.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube004_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh receiveShadow castShadow geometry={nodes.GaragesQuad.geometry} material={materials['Material.004']} position={[-44.35, 0.65, -53.94]} rotation={[0, -Math.PI / 2, 0]} scale={[5.67, 0.75, 7.23]} />
      <group position={[5.61, 0.65, -97.67]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube003.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube003_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-5.73, 0.65, -97.67]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube008.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube008_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-17.07, 0.65, -97.67]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube009.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube009_1.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-28.4, 0.65, -97.67]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube010.geometry} material={materials['Material.002']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube010_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh receiveShadow castShadow geometry={nodes.GaragesQuad001.geometry} material={materials['Material.004']} position={[-28.4, 0.65, -104.98]} rotation={[Math.PI, 0, Math.PI]} scale={[5.67, 0.75, 7.23]} />
      <group position={[35.93, 0.65, -97.66]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube012.geometry} material={materials['Material.006']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube012_1.geometry} material={materials['Material.005']} />
      </group>
      <group position={[24.6, 0.65, -97.66]} rotation={[Math.PI, 0, Math.PI]} scale={[4.36, 0.75, -0.15]}>
        <mesh receiveShadow castShadow geometry={nodes.Cube013.geometry} material={materials['Material.006']} />
        <mesh receiveShadow castShadow geometry={nodes.Cube013_1.geometry} material={materials['Material.005']} />
      </group>
      <mesh receiveShadow castShadow geometry={nodes.GaragesDouble.geometry} material={materials['Material.001']} position={[24.6, 0.58, -104.97]} rotation={[Math.PI, 0, Math.PI]} scale={[5.67, 0.75, 7.23]} />
    </group>
  )
})

useGLTF.preload('/Factory.glb')

export default Factory