// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { forwardRef } from 'react';
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({level, reference, ...props}) => {
  const { nodes, materials } = useGLTF("/Building Type 2 Lvl 2.gltf");
 
  const { opacity } = useSpring({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  })
  const opacityToMaterial = (opacity, mat) => {
    // console.log(opacity);
    // let mat = new MeshStandardMaterial(material);
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;

  return (
    <group name="objectGroup" ref={reference} {...props} scale={[scale, scale, scale]} dispose={null}>
      <group scale={[3, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials["osnovna bela boja"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials.trava}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials.zgrada}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023_1.geometry}
        material={materials.prozor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials["vrata.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024_1.geometry}
        material={materials.zgrada}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024_2.geometry}
        material={materials.prag}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024_3.geometry}
        material={materials["brava.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024_4.geometry}
        material={materials.staklo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.spratovi}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025_1.geometry}
        material={materials.zgrada}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025_2.geometry}
        material={materials["sivi zidovi"]}
      />
    </group>
  );
};

useGLTF.preload("/Building Type 2 Lvl 1.gltf");

export default Theme0;