// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({level, reference, ...props}) => {
  const { nodes, materials } = useGLTF('/store.glb')
 
  const { opacity } = useSpring({
    opacity: 1,
    from: {
      opacity: 0
    }
  })
  const opacityToMaterial = (opacity, mat) => {
    // console.log(opacity);
    // let mat = new MeshStandardMaterial(material);
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  return (
    <group name="objectGroup" ref={reference} {...props} scale={[props.scale, props.scale * (level*2+1), props.scale]}dispose={null}>
      <a.mesh receiveShadow geometry={nodes.Plane.geometry} material={opacity.to(o => opacityToMaterial(o, materials["grass.001"]))} scale={[30, 1, 30]} />
      <group position={[24.39, 0.59, -4.96]} rotation={[0.14, -0.16, 0.03]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials.brown))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials.green2))} />
      </group>
      <group position={[24.4, 0.59, 15.75]} rotation={[-0.06, 0.35, -0.02]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={opacity.to(o => opacityToMaterial(o, materials.brown))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder006_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials.green2))} />
      </group>
      <group position={[17.02, 0.59, 8.21]} rotation={[-0.13, 1.49, 0]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder007.geometry} material={opacity.to(o => opacityToMaterial(o, materials.brown))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder007_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials.green2))} />
      </group>
      <group position={[12.26, 0.59, 22.78]} rotation={[-0.06, 0.35, -0.02]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder008.geometry} material={opacity.to(o => opacityToMaterial(o, materials.brown))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cylinder008_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials.green2))} />
      </group>
      <group position={[-10, 0, 0]} scale={[14.8, 1, 25.15]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={opacity.to(o => opacityToMaterial(o, materials.Material))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube007_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials["Material.001"]))} />
      </group>
      <group position={[4.95, 5.53, 2.89]} scale={[0.2, 2.84, 3.2]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={opacity.to(o => opacityToMaterial(o, materials["brown.001"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube011_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials["shiny.001"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube011_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials["snow.001"]))} />
      </group>
      <group position={[4.95, 5.53, 16.89]} scale={[0.2, 2.84, 3.2]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube014.geometry} material={opacity.to(o => opacityToMaterial(o, materials["brown.003"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube014_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials["shiny.002"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube014_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials["snow.002"]))} />
      </group>
      <group position={[-24.86, 5.53, -5]} scale={[0.2, 2.84, 3.2]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube015.geometry} material={opacity.to(o => opacityToMaterial(o, materials["brown.004"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube015_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials["shiny.003"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube015_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials["snow.003"]))} />
      </group>
      <group position={[-24.86, 5.53, 17]} scale={[0.2, 2.84, 3.2]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={opacity.to(o => opacityToMaterial(o, materials["brown.005"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube016_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials["shiny.004"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube016_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials["snow.004"]))} />
      </group>
      <group position={[-24.86, 5.53, 6]} scale={[0.2, 2.84, 3.2]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube017.geometry} material={opacity.to(o => opacityToMaterial(o, materials["brown.006"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube017_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials["shiny.005"]))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube017_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials["snow.005"]))} />
      </group>
      <a.mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={opacity.to(o => opacityToMaterial(o, materials.Material))}
        position={[-6, 15.6, 23]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[15.15, 1, 15.15]}
      />
      <a.mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={opacity.to(o => opacityToMaterial(o, materials["rock.002"]))}
        position={[23.04, 0, 8.22]}
        rotation={[0, -0.38, 0]}
      />
      <a.mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone001.geometry}
        material={opacity.to(o => opacityToMaterial(o, materials["rock.002"]))}
        position={[21.82, 0, 25.87]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={1.68}
      />
      <a.mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={opacity.to(o => opacityToMaterial(o, materials["rock.001"]))}
        position={[10.68, -0.09, -3.86]}
        rotation={[0, -0.52, 0]}
        scale={1.78}
      />
      <a.mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={opacity.to(o => opacityToMaterial(o, materials["rock.001"]))}
        position={[10.67, -1.08, 17.07]}
        rotation={[0.36, 0.23, 0]}
        scale={1.78}
      />
      <group position={[5, 2.72, -20.16]} scale={[0.18, 1.16, 1]}>
        <a.mesh castShadow receiveShadow geometry={nodes.knob.geometry} material={opacity.to(o => opacityToMaterial(o, materials.brown))} />
        <a.mesh castShadow receiveShadow geometry={nodes.knob_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials.shiny))} />
        <a.mesh castShadow receiveShadow geometry={nodes.knob_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials.snow))} />
        <a.mesh castShadow receiveShadow geometry={nodes.knob_3.geometry} material={opacity.to(o => opacityToMaterial(o, materials.floortile))} />
      </group>
      <group position={[4.95, 5.53, -9.11]} scale={[0.2, 2.84, 3.2]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={opacity.to(o => opacityToMaterial(o, materials.brown))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube006_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials.shiny))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube006_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials.snow))} />
      </group>
      <group position={[-24.86, 5.53, -16]} scale={[0.2, 2.84, 3.2]}>
        <a.mesh castShadow receiveShadow geometry={nodes.Cube040.geometry} material={opacity.to(o => opacityToMaterial(o, materials.brown))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube040_1.geometry} material={opacity.to(o => opacityToMaterial(o, materials.shiny))} />
        <a.mesh castShadow receiveShadow geometry={nodes.Cube040_2.geometry} material={opacity.to(o => opacityToMaterial(o, materials.snow))} />
      </group>
    </group>
  );
}

useGLTF.preload('/store.glb')
export default Theme0