// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({level, reference, ...props}) => {
  const { nodes, materials } = useGLTF("/Shop.gltf");
 
  const { opacity } = useSpring({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  })
  const opacityToMaterial = (opacity, mat) => {
    // console.log(opacity);
    // let mat = new MeshStandardMaterial(material);
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;

  return (
    <group name="objectGroup" ref={reference} {...props} scale={[ scale, scale, scale ]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_1.geometry}
        material={materials["osnovna bela boja"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_2.geometry}
        material={materials.trava}
      />
      <group scale={0.82}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067.geometry}
          material={materials.zidovi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_1.geometry}
          material={materials["okvir znaka"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_2.geometry}
          material={materials["pozadina znak"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_3.geometry}
          material={materials["gore oko znaka"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_4.geometry}
          material={materials["sivi zidovi"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube067_5.geometry}
          material={materials.cokna}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials["cerada red"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024_1.geometry}
        material={materials["cerada bela"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lajsana.geometry}
        material={materials.stangla}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials.saksije}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018_1.geometry}
        material={materials.stablo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018_2.geometry}
        material={materials.cempres}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018_3.geometry}
        material={materials.zemlja}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.002"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081.geometry}
        material={materials.vrata}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081_1.geometry}
        material={materials.stokovi}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081_2.geometry}
        material={materials["staklo.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081_3.geometry}
        material={materials.brava}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube081_4.geometry}
        material={materials["prag.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube082.geometry}
        material={materials.windows}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube082_1.geometry}
        material={materials["staklo.002"]}
      />
    </group>
  );
}

useGLTF.preload('/Store.gltf')
export default Theme0