// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({level, reference, ...props}) => {
  const { nodes, materials } = useGLTF("/Office Building Lvl 2.gltf");
 
  const { opacity } = useSpring({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  })
  const opacityToMaterial = (opacity, mat) => {
    // console.log(opacity);
    // let mat = new MeshStandardMaterial(material);
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;

  return (
    <group name="objectGroup" ref={reference} {...props} scale={[ scale, scale, scale ]} dispose={null}>
      <group scale={[3, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials["osnovna bela boja"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={materials.prag}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.cempres}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006_1.geometry}
        material={materials.zemlja}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006_2.geometry}
        material={materials["crkva zidovi"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006_3.geometry}
        material={materials.Bark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials["sivi zidovi 2"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040_1.geometry}
        material={materials.kolica}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040_2.geometry}
        material={materials.staklo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040_3.geometry}
        material={materials.prag}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11002.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11002_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11003.geometry}
          material={materials["Bark.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11003_1.geometry}
          material={materials["Tree.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["sivi zidovi 2"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011_1.geometry}
        material={materials.trava}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials["sivi zidovi"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_1.geometry}
        material={materials["sivi zidovi 2"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_2.geometry}
        material={materials["metalna ograda"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041_3.geometry}
        material={materials.staklo}
      />
    </group>
  );
}

useGLTF.preload('/Office Building Lvl 2.gltf')

export default Theme0