// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({level, reference, ...props}) => {
  const { nodes, materials } = useGLTF("/Office Building Lvl 1.gltf");
 
  const { opacity } = useSpring({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  })
  const opacityToMaterial = (opacity, mat) => {
    // console.log(opacity);
    // let mat = new MeshStandardMaterial(material);
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;

  return (
    <group name="objectGroup" ref={reference} {...props} scale={[ scale, scale, scale ]} dispose={null}>
      <group scale={[3, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials["osnovna bela boja"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials.prag}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials.staklo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037_1.geometry}
        material={materials["sivi zidovi"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037_2.geometry}
        material={materials["krov zgrade"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.cempres}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005_1.geometry}
        material={materials.zemlja}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005_2.geometry}
        material={materials["crkva zidovi"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005_3.geometry}
        material={materials["kora drveta"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials.staklo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_1.geometry}
        material={materials.kolica}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_2.geometry}
        material={materials.prag}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038_3.geometry}
        material={materials["sivi zidovi"]}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11.geometry}
          material={materials.Bark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11_1.geometry}
          material={materials.Tree}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11001.geometry}
          material={materials["Bark.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11001_1.geometry}
          material={materials["Tree.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["sivi zidovi"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009_1.geometry}
        material={materials.trava}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone011.geometry}
        material={materials["krosnja cempres"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone011_1.geometry}
        material={materials.Bark}
      />
    </group>
  );
}

useGLTF.preload('/Office Building Lvl 1.gltf')

export default Theme0