// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({ reference, status, ...props}) => {
  const { nodes, materials } = useGLTF("/Park 3x4.gltf");

  const [ { opacity }, springApi ] = useSpring(() => ({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  }))

  const opacityToMaterial = (opacity, mat) => {
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;
  
  return (
    <group name="objectGroup" ref={reference} {...props} scale={[ scale, scale, scale ]} rotation={[props.rotation[0], props.rotation[1] + Math.PI/2, props.rotation[2]]} dispose={null}>
      <group scale={[3, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018.geometry}
          material={materials["osnovna bela boja"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_1.geometry}
          material={materials.trava}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_2.geometry}
          material={materials["crkva zidovi"]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11023.geometry}
          material={materials["Bark.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11023_1.geometry}
          material={materials["Tree.003"]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11024.geometry}
          material={materials["Bark.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11024_1.geometry}
          material={materials["Tree.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone010.geometry}
        material={materials["vrata.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone010_1.geometry}
        material={materials["krosnja cempres"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere013.geometry}
        material={materials["kora drverata braon"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere013_1.geometry}
        material={materials.krosnja}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11025.geometry}
          material={materials["Bark.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11025_1.geometry}
          material={materials["Tree.004"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056.geometry}
        material={materials.spratovi}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube056_1.geometry}
        material={materials["tamni crep"]}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11026.geometry}
          material={materials["Bark.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11026_1.geometry}
          material={materials["Tree.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LAKE_WATER.geometry}
        material={materials.VODA}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lake_stones.geometry}
        material={materials.zemlja}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GRASS_1.geometry}
        material={materials["bf_grass.002"]}
        position={[-0.01, 0, 0]}
        rotation={[0, -1.27, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Low_poly_tree002.geometry}
        material={materials["Material.001"]}
        position={[0.01, 0, -0.01]}
        scale={0.19}
      />
      <group position={[0.03, 0, -0.02]} scale={0.16}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034.geometry}
          material={materials["Low Poly Grass_Grass"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane034_1.geometry}
          material={materials["Low Poly Grass_Flower"]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/Park 3x4.gltf");

export default Theme0