// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({ reference, status, ...props}) => {
  const { nodes, materials } = useGLTF("/Park 4x4.gltf");

  const [ { opacity }, springApi ] = useSpring(() => ({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  }))

  const opacityToMaterial = (opacity, mat) => {
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;
  
  return (
    <group name="objectGroup" ref={reference} {...props} scale={[ scale, scale, scale ]} rotation={[props.rotation[0], props.rotation[1] + Math.PI/2, props.rotation[2]]} dispose={null}>
      <group scale={[3, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials["osnovna bela boja"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_1.geometry}
          material={materials.trava}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_2.geometry}
          material={materials["crkva zidovi"]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11027.geometry}
          material={materials["Bark.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11027_1.geometry}
          material={materials["Tree.003"]}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11028.geometry}
          material={materials["Bark.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11028_1.geometry}
          material={materials["Tree.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone012.geometry}
        material={materials["vrata.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone012_1.geometry}
        material={materials["krosnja cempres"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere014.geometry}
        material={materials["kora drverata braon"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere014_1.geometry}
        material={materials.krosnja}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057.geometry}
        material={materials.spratovi}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube057_1.geometry}
        material={materials["tamni crep"]}
      />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11030.geometry}
          material={materials["Bark.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree_lp_11030_1.geometry}
          material={materials["Tree.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LAKE_WATER001.geometry}
        material={materials.VODA}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lake_stones001.geometry}
        material={materials.zemlja}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GRASS_1001.geometry}
        material={materials["bf_grass.002"]}
        position={[-0.01, 0, 0]}
        rotation={[0, -1.27, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059.geometry}
        material={materials["crkva zidovi"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube059_1.geometry}
        material={materials["Kov kuce crep"]}
      />
      <group scale={0.16}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060.geometry}
          material={materials["cerada red"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_1.geometry}
          material={materials["zuti market"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061.geometry}
        material={materials["zuti market"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061_1.geometry}
        material={materials["cerada red"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061_2.geometry}
        material={materials.supermarket}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube061_3.geometry}
        material={materials["metalna ograda"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.kvaka}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010_1.geometry}
        material={materials.supermarket}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010_2.geometry}
        material={materials["Kov kuce crep"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010_3.geometry}
        material={materials.FONTANA}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Low_poly_tree003.geometry}
        material={materials["Material.001"]}
        position={[0.01, 0, -0.01]}
        scale={0.19}
      />
      <group position={[0.03, 0, -0.02]} scale={0.16}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials["Low Poly Grass_Grass"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020_1.geometry}
          material={materials["Low Poly Grass_Flower"]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/Park 4x4.gltf");

export default Theme0