import Head from 'next/head';
import Nav from "../components/nav/Nav";
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />
        <h2 id="about">About</h2>
        <p>About us section</p>
        <h2 id="faq">FAQ</h2>
        <p>Freaquently asked questions</p>
        <h2 id="contact">Contact us</h2>
        <p>Feel free to contact us</p>
      </main>
      </div>
  )
}