// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({ reference, status, ...props}) => {
  const { nodes, materials } = useGLTF("/House Lvl 2.gltf");

  const [ { opacity }, springApi ] = useSpring(() => ({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  }))

  const opacityToMaterial = (opacity, mat) => {
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;
  
  return (
    <group name="objectGroup" ref={reference} {...props} scale={[ scale, scale, scale ]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["osnovna bela"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002_1.geometry}
        material={materials["trava.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ograda001.geometry}
        material={nodes.ograda001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002.geometry}
        material={materials["kora drveta"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002_1.geometry}
        material={materials.krosnja}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["tamni crep"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006_1.geometry}
        material={materials["zidovi kuce"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["okviri prozora"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007_1.geometry}
        material={materials["staklo.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Vrata kuce"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008_1.geometry}
        material={materials["stok vrata"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008_2.geometry}
        material={materials["staklena vrata"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008_3.geometry}
        material={materials.kvaka}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008_4.geometry}
        material={materials["prag.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["kapija graze"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009_1.geometry}
        material={materials["stokovi kapije"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009_2.geometry}
        material={materials["garaza vrata"]}
      />
    </group>
  )
}

useGLTF.preload("/House Lvl 2.gltf");

export default Theme0