// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({ reference, status, ...props}) => {
  const { nodes, materials } = useGLTF("/House Lvl 1.gltf");

  const [ { opacity }, springApi ] = useSpring(() => ({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  }))

  const opacityToMaterial = (opacity, mat) => {
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;
  
  return (
    <group name="objectGroup" ref={reference} {...props} scale={[ scale, scale, scale ]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["osnovna bela boja"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_1.geometry}
        material={materials.trava}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ograda.geometry}
        material={materials["bela ograda"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={materials["kora drverata braon"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001_1.geometry}
        material={materials["krosnja cempres"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Kov kuce crep.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_1.geometry}
        material={materials["Zidovi kuce krem"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube080.geometry}
        material={materials["OKVIR PROZORA"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube080_1.geometry}
        material={materials["staklo prozori"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083.geometry}
        material={materials["ulazna vrata"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083_1.geometry}
        material={materials.prag}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083_2.geometry}
        material={materials["stokovi "]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083_3.geometry}
        material={materials["brava.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube083_4.geometry}
        material={materials.staklo}
      />
    </group>
  )
}

useGLTF.preload("/House Lvl 1.gltf");

export default Theme0