// edited by the addingAnimations script!
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

import { useSpring } from '@react-spring/three'
import { a } from '@react-spring/three'

const Theme0 = ({ reference, ...props}) => {
  const { nodes, materials } = useGLTF("/Building Type 1 Lvl 1.gltf");
 
  const { opacity } = useSpring({
    opacity: 1,
    // from: {
      // opacity: 0
    // }
  })
  const opacityToMaterial = (opacity, mat) => {
    // console.log(opacity);
    // let mat = new MeshStandardMaterial(material);
    mat.transparent = true;
    mat.opacity = opacity;
    return mat;
  }

  const scale = 2.45;

  return (
    <group name="objectGroup" ref={reference} {...props} rotation={[ props?.rotation[0], props?.rotation[1]+Math.PI/2, props?.rotation[2] ]} scale={[scale, scale, scale]} dispose={null}>
      <group scale={[3, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["osnovna bela boja"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials.trava}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone001.geometry}
        material={materials.cempres}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone001_1.geometry}
        material={materials.stablo}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone002.geometry}
        material={materials.cempres}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone002_1.geometry}
        material={materials["kora drverata braon"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials.zgrada}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010_1.geometry}
        material={materials.spratovi}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010_2.geometry}
        material={materials["krov zgrade"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["okviri prozora.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011_1.geometry}
        material={materials.prozori}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["vrata.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013_1.geometry}
        material={materials["stokovi.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013_2.geometry}
        material={materials["prag.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013_3.geometry}
        material={materials.prozor}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013_4.geometry}
        material={materials["brava.001"]}
      />
    </group>
  );
}

useGLTF.preload('/Building Type 1 Lvl 1.gltf')
export default Theme0